Fix: Update asset path for flags in issue #172
razorpay/i18nify pull request #177
Opened 2024-10-13 10:40 UTC by RashidHussain786

# Description

This PR addresses the issue of flag images not being displayed correctly. The changes made ensure that the correct paths are set for the flag assets, which allows them to be included in the build output. This resolves the visibility issue and improves user experience when selecting flags.

## Changes Made

- Updated the asset path for flag images in the Vite configuration file to ensure correct inclusion in the build.
- Adjusted the build script to reference the updated flag paths.

![fixImg1](https://github.com/user-attachments/assets/ea1f064c-85ff-4e3f-a552-fa89c29d3e39)
![fixImg2](https://github.com/user-attachments/assets/3a02d52d-5479-4d19-a22e-738ec11598bd)

| Title           | --- |
| ---------------------- | --- |
| JIRA link              | NA  |
| Slack thread (if any)  | NA  |
| Product spec           | NA  |
| Tech spec/One-pager    | NA  |
| Bundle Size Difference | NA  |
| Fixes Issue            | [#172](https://geosmart.razorpay.com/#/phone/isValidPhoneNumber)  |

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## How Has This Been Tested?

- Verified that the correct flag images are displayed after the build process.
- Tested on major browsers (Chrome and Firefox).
- Confirmed the issue does not reoccur in a local development environment.

- [x] Is your change backward compatible ?
- [x] Tested on major browsers (Chrome, Firefox, Safari, IE) ?
- [ ] Tested in a consumer application(s) ?

## Additional Notes

The changes have been validated locally, and the flags now load as expected. If further adjustments are required, please let me know.

## Checklist:

- [ ] Add Jira ID(s) in PR title and in the description?
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code is written in TypeScript and follows the coding standards of the project.
- [ ] I have added relevant documentation and updated the README if necessary.
- [ ] My commit messages are clear and follow the project's commit message conventions.
- [ ] Is any external library added?
- [ ] My changes do not introduce any new runtime errors or warnings.
- [ ] All relevant unit tests have been added/updated in my PR for the change.
- [ ] Any Screenshots (mobile & desktop) required for PR? If yes, have you added the respective screenshots ?
- [ ] Any manual dev testing done by you on beta/func environment?
- [ ] Reviewer added (SLA 2 days)

## Reviewer Checklist

- [ ] Sufficient QA/Dev-Testing is done with proof (test cases list)
- [ ] Ensure that the change in bundle size falls within the acceptable range.

---

## PR Title Format

Format: `(fix: fix flag image loading issue)`

Types can be as follows:

- `feat`: (new feature for the user, not a new feature for build script)
- `fix`: (bug fix for the user, not a fix to a build script)
- `docs`: (changes to the documentation)
- `style`: (formatting, missing semi colons, etc; no production code change)
- `refactor`: (refactoring production code, eg. renaming a variable)
- `test`: (adding missing tests, refactoring tests; no production code change)
- `chore`: (updating grunt tasks etc; no production code change)

2024-10-13 16:21 UTC, RgnDunes requested changes
<img width="183" alt="Screenshot 2024-10-13 at 9 50 16 PM" src="https://github.com/user-attachments/assets/de5a71c2-027a-4961-94f4-ef3805944a47">

Test thoroughly

2024-10-13 17:37 UTC, RashidHussain786 commented
Hi @RgnDunes,

You're correct that we need to build the i18nify-playground. In the current PR, I only made changes to the configuration file (vite.config.js) to address the flag image path issue, but I haven't included the built files.

The reason I didn't include the build is that generally, we avoid committing build artifacts (like the dist folder) directly into the repository, as these can be generated during the deployment process.

Would you prefer I include the built files in the PR, or should we rely on the existing build pipeline to generate them when the changes are merged?

Looking forward to your guidance on this!

2024-10-17 05:09 UTC, RgnDunes commented
https://github.com/razorpay/i18nify/pull/177#issuecomment-2409062416

@RashidHussain786 it's a simple react application running it locally I should see the changes working, how is it linked with the build files ? 

build is required only for deployment purpose and not for testing purpose. Once I spin up the server on local I should see the changes working

2024-10-17 09:51 UTC, RashidHussain786 commented
Hi @RgnDunes,

The issue occurs because the flag images are stored outside the `public` folder (in `i18nify-data/assets/flags`). React expects static assets to be in `public` to make them accessible. When I set up the code and ran it, I discovered during debugging that the assets folder did not contain the flag folder, which led me to identify the issue.

## Two options to fix:

1. **Modify the build process:** Automatically copy the flag images from `i18nify-data/assets/flags` to `public/assets/flags` using:

   ```javascript
   { src: '../../i18nify-data/assets/flags/*', dest: 'public/assets/flags' },
2. **Manually copy the files:**  you can manually move the flag images into `public/assets/flags` . This works for local testing but isn’t ideal for deployment.

Let me know your preference!

2025-04-08 09:22 UTC, closed without merging