Added locale for all countries [Fixes #176]
razorpay/i18nify pull request #178
Opened 2024-10-13 22:27 UTC by sarthak-kumar-shailendra

# Description
Added locale of all the countries present in the database (https://github.com/razorpay/i18nify/blob/master/i18nify-data/country/metadata/data.json) and using the same values to create the LANGS array of obj. [Fixes #176]

## Changes Made
Added two ss to show of selecting different country.
<img width="1141" alt="Screenshot 2024-10-14 at 3 46 36 AM" src="https://github.com/user-attachments/assets/5aa8659d-f184-4a8e-8626-82abc212f925">
<img width="478" alt="Screenshot 2024-10-14 at 3 49 15 AM" src="https://github.com/user-attachments/assets/9b6bc2c4-4e0c-44fa-9d02-f579f53c0ebd">

List the main changes made in this pull request.

| Title                  | --- |
| ---------------------- | --- |
| JIRA link              | NA  |
| Slack thread (if any)  | NA  |
| Product spec           | NA  |
| Tech spec/One-pager    | NA  |
| Bundle Size Difference | NA  |
| Fixes Issue            | NA  |

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Is your change backward compatible ?
- [ ] Tested on major browsers (Chrome, Firefox, Safari, IE) ?
- [ ] Tested in a consumer application(s) ?

## Additional Notes

Any additional information that would be helpful for the reviewer.

## Checklist:

- [ ] Add Jira ID(s) in PR title and in the description?
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code is written in TypeScript and follows the coding standards of the project.
- [ ] I have added relevant documentation and updated the README if necessary.
- [ ] My commit messages are clear and follow the project's commit message conventions.
- [ ] Is any external library added?
- [ ] My changes do not introduce any new runtime errors or warnings.
- [ ] All relevant unit tests have been added/updated in my PR for the change.
- [ ] Any Screenshots (mobile & desktop) required for PR? If yes, have you added the respective screenshots ?
- [ ] Any manual dev testing done by you on beta/func environment?
- [ ] Reviewer added (SLA 2 days)

## Reviewer Checklist

- [ ] Sufficient QA/Dev-Testing is done with proof (test cases list)
- [ ] Ensure that the change in bundle size falls within the acceptable range.

---

## PR Title Format

Format: `<type>: <subject>`

Types can be as follows:

- `feat`: (new feature for the user, not a new feature for build script)
- `fix`: (bug fix for the user, not a fix to a build script)
- `docs`: (changes to the documentation)
- `style`: (formatting, missing semi colons, etc; no production code change)
- `refactor`: (refactoring production code, eg. renaming a variable)
- `test`: (adding missing tests, refactoring tests; no production code change)
- `chore`: (updating grunt tasks etc; no production code change)

2024-10-13 22:29 UTC, sarthak-kumar-shailendra commented
@RgnDunes Please review

2024-10-17 05:05 UTC, RgnDunes requested changes
Beside flag can we have some text that describes the locale. Maybe the value of locale beside flag image

2024-10-17 06:42 UTC, sarthak-kumar-shailendra commented
> Beside flag can we have some text that describes the locale. Maybe the value of locale beside flag image
I have made the changes. Please check now @RgnDunes

2024-10-28 18:12 UTC, sarthak-kumar-shailendra commented
Please check now @RgnDunes

2024-10-30 18:52 UTC, sarthak-kumar-shailendra commented
@saurabhdaware Please review

2024-11-30 20:18 UTC, sarthak-kumar-shailendra commented
@varunkumark1997 @RgnDunes can you guys please review this?

2025-04-08 09:22 UTC, closed without merging

2025-04-08 09:39 UTC, sarthak-kumar-shailendra commented
@RgnDunes why have we closed this?